### ISSUE TITLE
초기 세팅

### ISSUE THREAD

**Issue by ByungdooGong** [ByungdooGong/React-Native-Study#1]
## NVM 설치
1.설치
```
 sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
export NVM_DIR="$HOME/.nvm"
```
2. 환경변수 설정
```
vi ~/.bash_profile
```
```sh
# bash_profile

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
```
3. 환경변수 적용
```
source ~/.bash_profile
```

## cocoapod 설치
```
sudo gem install cocoapods -v 1.8.4
```

## react-native 설치
```
npm install -g react-native-cli
```

**Comment by ByungdooGong** [comment]
## [Trouble Shooting]
```react-native init --version 0.65.1 my_first_app``` 명령어 실행시 아래 에러 발생
```
You are currently running Node v10.15.1 but React Native requires >=12. Please use a supported version of Node.
See https://facebook.github.io/react-native/docs/getting-started.html
/Users/user/my_first_app/node_modules/metro/src/Server.js:350
  processRequest = (req, res, next) => {
                 ^

SyntaxError: Unexpected token =
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```
- node 재설치
```
nvm install 12.19.1
```
- 버전 변경
```
~ nvm --version
0.33.11
➜  ~ nvm ls
->     v10.15.1
       v12.19.1
default -> 10.15.1 (-> v10.15.1)
node -> stable (-> v12.19.1) (default)
stable -> 12.19 (-> v12.19.1) (default)
iojs -> N/A (default)
lts/* -> lts/gallium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12 (-> N/A)
lts/fermium -> v14.19.1 (-> N/A)
lts/gallium -> v16.14.2 (-> N/A)
➜  ~ nvm use 12.19.1
Now using node v12.19.1 (npm v6.14.8)
➜  ~ node --version
v12.19.1
```


- react-native 재설치
```
npm install -g react-native-cli
```

**Comment by ByungdooGong** [comment]
## [Trouble Shooting]
- cocoapods 삭제 ```sudo gem uninstall cocoapods``` 후 재설치 에러발생
```
Fetching public_suffix-4.0.7.gem
Building native extensions. This could take a while...
ERROR:  Error installing cocoapods:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220417-8105-p05cap.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

- brew 로 설치하면 된다고 해서 우선 홈브류 설치 https://brew.sh/index_ko
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
```
brew cleanup -d -v
```
```
brew install cocoapods
```
```
brew link --overwrite cocoapods
```

- 이 후 ```react-native init --version 0.65.1 my_first_app``` 다시 해보니 성공
<img width="904" alt="스크린샷 2022-04-17 오전 11 33 21" src="https://user-images.githubusercontent.com/47800190/163697728-7ad325e8-7b22-43ff-8245-7e8de7c2ecb2.png">

**Comment by ByungdooGong** [comment]
## [Trouble Shooting]
- init 프로젝트까지는 성공했으나 run-android 시에 에러가 발생했다. ```SyntaxError 어쩌구 저쩌구```
- node 버전 문제인듯 https://github.com/facebook/metro/issues/703
- node 버전 높여서 추가
```
~ nvm install 12.19.1
~ nvm use 12.19.1
~ nvm alias default 12.19.1
```
- 다시 react-native run-android를 해보았으나 아래 에러 발생
```
BUILD FAILED in 26s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/user/my_first_app/android/local.properties'.
```
- 찾아보니 local.properties가 없어서 문제 발생 https://eso0609.tistory.com/92
- ~/my_first_app/android 경로 아래에 local.properties 추가
```
sdk.dir=/Users/user/Library/Android/sdk
```

- 그래도 여전히 sdk 경로를 못찾는다는 에러 발생(나는 터미널로 zsh로 사용하고 있는데 bash_profile을 편집하고 있으니 반영이 안되는 거였음.)
- zshrc 수정
```
~ open ~/.zshrc
```
아래 내용 추가
```
export ANDROID_HOME=/Users/user/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
```
```
~ touch ~/.zshrc
~ source ~/.zshrc
```

**Comment by ByungdooGong** [comment]
## ios 에러뜰때

```
~ brew install yarn
~ npm install react-native-codegen
```

Try delete ```node_modules``` and ```ios/Pods```
then ```yarn install && npx pod-install```

- ios/podFile 내용 아래 주석처리
```
# use_flipper!()

# post_install do |installer|
#   react_native_post_install(installer)
# end
```
